// DO NOT EDIT. This file is generated by remix-deno-jit.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `deno task dev`.

import * as serverEntry from "./app/entry.server.tsx";
import * as route0 from "./app/root.tsx";
import * as route1 from "./app/routes/projects.$project.tsx";
import * as route2 from "./app/routes/$section.tsx";
import * as route3 from "./app/routes/index.tsx";
import * as route4 from "./app/routes/$.tsx";

export const entry = { module: serverEntry };
export const routes = {
	"root": {
		id: "root",
		module: route0,
		file: "./app/root.tsx",
	},
	"routes/projects/$project": {
		id: "routes/projects/$project",
		path: "projects/:project",
		parentId: "root",
		module: route1,
		file: "./app/routes/projects.$project.tsx",
	},
	"routes/$section": {
		id: "routes/$section",
		path: ":section",
		parentId: "root",
		module: route2,
		file: "./app/routes/$section.tsx",
	},
	"routes/index": {
		id: "routes/index",
		index: true,
		parentId: "root",
		module: route3,
		file: "./app/routes/index.tsx",
	},
	"routes/$": {
		id: "routes/$",
		path: ":",
		parentId: "root",
		module: route4,
		file: "./app/routes/$.tsx",
	},
};
export const assets = {
  entry: { imports: [], module: "/entry.client.js" },
  routes: {
		"root": {
			id: "root",
			imports: [],
			module: "/root.js",
			hasAction: "action" in route0,
			hasLoader: "loader" in route0,
			hasCatchBoundary: "CatchBoundary" in route0,
			hasErrorBoundary: "ErrorBoundary" in route0,
		},
			"routes/projects/$project": {
			id: "routes/projects/$project",
			path: "projects/:project",
			parentId: "root",
			imports: [],
			module: "/routes/projects/$project.js",
			hasAction: "action" in route1,
			hasLoader: "loader" in route1,
			hasCatchBoundary: "CatchBoundary" in route1,
			hasErrorBoundary: "ErrorBoundary" in route1,
		},
			"routes/$section": {
			id: "routes/$section",
			path: ":section",
			parentId: "root",
			imports: [],
			module: "/routes/$section.js",
			hasAction: "action" in route2,
			hasLoader: "loader" in route2,
			hasCatchBoundary: "CatchBoundary" in route2,
			hasErrorBoundary: "ErrorBoundary" in route2,
		},
			"routes/index": {
			id: "routes/index",
			index: true,
			parentId: "root",
			imports: [],
			module: "/routes/index.js",
			hasAction: "action" in route3,
			hasLoader: "loader" in route3,
			hasCatchBoundary: "CatchBoundary" in route3,
			hasErrorBoundary: "ErrorBoundary" in route3,
		},
			"routes/$": {
			id: "routes/$",
			path: ":",
			parentId: "root",
			imports: [],
			module: "/routes/$.js",
			hasAction: "action" in route4,
			hasLoader: "loader" in route4,
			hasCatchBoundary: "CatchBoundary" in route4,
			hasErrorBoundary: "ErrorBoundary" in route4,
		},		
},
};
export const future = { v2_errorBoundary: true };
